version: '3.7'

services:

  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: '3333'
    image: timurkash/pow-client:0.0.1
    restart: 'no'
    depends_on:
      - server
    networks:
      - pow

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: '3333'
      CACHE_HOST: "redis"
      CACHE_PORT: '6379'
#    ports:
#      - '3333:3333'
    image: timurkash/pow-server:0.0.1
    restart: 'no'
    depends_on:
      - redis
    networks:
      - pow

  redis:
      image: redis
#      ports:
#        - '6379:6379'
      networks:
        - pow

networks:
  pow:
